platform :ios, '8.0'
target 'UniversalApp' do
pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
#pod 'NIMSDK', '~> 3.7.0'
pod 'YTKNetwork'
pod 'SDWebImage', '~>3.8'
pod 'FMDB'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'MJExtension'
pod 'LGAlertView'
pod 'LFMediaEditingController'
pod 'YMCitySelect'
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'
pod 'BaiduMapKit' #百度地图SDK

 pod 'UMengUShare/UI'
# pod 'UMengUShare/Social/WeChat'
 pod 'UMengUShare/Social/QQ'
 pod 'UMengUShare/Social/Sina'
 pod 'UMengUShare/Social/Email'
 pod 'UMengUShare/Social/SMS'
 pod 'JPush'
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 


end
